[KAN-4] Changed get_notams to request one location's notams.
OU2024Capstone/notamSort pull request #17
Opened 2024-02-24 21:58 UTC by Zombiepro89

This is useful so that the function is generic,
thus it can be used for depature, arrival, and in-flight notam requests.

Added a skeleton function for front-end and back-end connection. Once we're ready to connect the front and back-end, we can call the start_notam_request_path() function which will call the necessary functions and return the output the front-end is expecting.
This function should be built on in future commits.

2024-02-25 00:47 UTC, JamesJWilliams3000 commented on notamFetch.py
> +def start_notam_request_path(departure_airport, arrival_airport) -> list:
The function name seems unclear to me, if this is the function meant to be called by the frontend. `start_notam_request_path` doesn't imply that it is going to return a sorted list of notams.

2024-02-25 00:58 UTC, JamesJWilliams3000 commented on notamFetch.py
> +    request_longitude_latitude expects a tuple of the form (log : float, lat : float)
I feel like `request_longitude_latitude` needs to be an explicit object, both for clearer documentation and to prevent errors. For example:
`request_longitude_latitude.latitude` and `request_longitude_latitude.longitude` are clearer than `request_longitude_latitude[0]` and `request_longitude_latitude[1]`. This also prevents a longitude being assigned to `request_longitude_latitude[0]` by mistake.

As an object, we can also constrain `request_longitude_latitude` values to float, so that we get an error when the object is initialized, as opposed to error checking anytime we need to use `request_longitude_latitude`.

2024-02-25 01:00 UTC, JamesJWilliams3000 commented on notamFetch.py
> +    if(not (airport_code is None)):
This isn't easy to read. (genuinely trying to be helpful, not mean)

2024-02-25 01:21 UTC, JamesJWilliams3000 commented on notamFetch.py
> +        return send_api_request(request_longitude_latitude)
I really think we should use method overloading here and try to minimize the number of things `get_notams()` is doing.
My idea:
```
def get_notams(request_longitude_latitude) -> list:
    # error handling, etc
    return send_api_request(request_longitude_latitude)
```
```
def get_notams(airport_code) -> list:
    # get `request_longitude_latitude` from `airport_code`, or raise an Exception if invalid
    return get_notams(request_longitude_latitude)
```

^ note at the end I called `get_notams` and not `send_api_request`, so that we guarantee the same functionality across both `get_notams`, if we ever make changes in the future.

2024-02-25 01:36 UTC, Zombiepro89 commented on notamFetch.py
> +        return send_api_request(request_longitude_latitude)
That was the idea at first, but, unfortunately, python does not support overloading functions, so this is the best next option. I don't like that I have to have that if statement at the beginning, but, without extra libraries, this seems to be the best way to do it. But I do absolutely agree with your ideas.

2024-02-25 01:37 UTC, JamesJWilliams3000 requested changes
I left a few comments for my review, mostly regarding `request_longitude_latitude`. 

I also think we should reconsider our function names, as `start_notam_request_path` and `get_notams` don't seem very clear on what they do at the moment. It doesn't seem obvious that `get_notams` shouldn't be called from the frontend, and `start_notam_request_path` doesn't sound like a function that will return a complete and sorted list of notams to the frontend.

2024-02-25 01:38 UTC, Zombiepro89 commented on notamFetch.py
> +    if(not (airport_code is None)):
Is it the parentheses that make it difficult to read? Would it be better as `not airport_code is None`?

2024-02-25 01:39 UTC, Zombiepro89 commented on notamFetch.py
> +    request_longitude_latitude expects a tuple of the form (log : float, lat : float)
Okay, I can do that. That's a pretty simple fix. Would the Notam object also utilize this new object?

2024-02-25 01:42 UTC, Zombiepro89 commented on notamFetch.py
> +def start_notam_request_path(departure_airport, arrival_airport) -> list:
Yeah, I wasn't sure what to call this function. I can't think of a good name for it at the moment, do you have any suggestions?

2024-02-25 01:57 UTC, JamesJWilliams3000 commented on notamFetch.py
> +        return send_api_request(request_longitude_latitude)
I went looking around, and it looks like as of Python 3.4 we can do overloading [(heres the documentation)](https://peps.python.org/pep-0443/). We need to import `functools`, but its a part of the Python standard library and I didn't need to install anything to run the example code from the link above.

So we could use something like

```
@singledispatch
def get_notams(request_longitude_latitude) -> list:

@get_notams.register(str)
def _(airport_code) -> list:
```

2024-02-25 02:24 UTC, JamesJWilliams3000 commented on notamFetch.py
> +def start_notam_request_path(departure_airport, arrival_airport) -> list:
I actually think swapping the names might work, as `get_notams` only returns part of our complete notam list

2024-02-25 02:28 UTC, JamesJWilliams3000 commented on notamFetch.py
> +    request_longitude_latitude expects a tuple of the form (log : float, lat : float)
I don't think so, as the Notam object just hold the properties meant for sorting/viewing, and the `location` property of the notam comes from the issuing airport/location (so the lat/long we use for middle points won't be equivalent to the `location` property that the faa returns). I think the `request_longitude_latitude` object would be used for calculating middle points (so any middle point(s) we find are stored as a `request_longitude_latitude` object), and for `get_notams`.

2024-02-25 02:38 UTC, JamesJWilliams3000 commented on notamFetch.py
> +    if(not (airport_code is None)):
I think it was more the entire `(not (airport_code is None))`; double negatives are difficult to read. 
According to [PEP 8:](https://peps.python.org/pep-0008/#programming-recommendations)

> For sequences, (strings, lists, tuples), use the fact that empty sequences are false:
> ```
> # Correct:
> if not seq:
> if seq:
> # Wrong:
> if len(seq):
> if not len(seq):
> ```

Since `airport_code` will be a string, using ```if not airport_code: ``` should be equivalent. 
IMO, I prefer ```if airport_code == "":``` , as it makes it obvious we are checking for an empty string.

2024-02-25 17:42 UTC, tanminivan commented
Good comments so far. I'm purposely withholding my comments to give others on the team a chance to review first. 🙂

2024-02-25 18:36 UTC, aidanperkins commented on notamFetch.py
> +        return send_api_request(request_longitude_latitude)
you can also do type enforcement for the different functions like this.
`def get_notams(request_longitude_latitude: tuple) -> list:`
`def _(airport_code: str) -> list: `

2024-02-25 18:52 UTC, aidanperkins commented on notamFetch.py
> +    if(type(request_longitude_latitude) is tuple and len(request_longitude_latitude) == 2
Since we raise an exception and return nothing when the request fails do we still need to check that the request_longitude_latitude is in the correct form?

2024-02-25 18:52 UTC, aidanperkins commented on notamFetch.py
> +def start_notam_request_path(departure_airport, arrival_airport) -> list:
Maybe change `get_notams` to `get_notam_at` and change `start_notam_request_path` to `get_notams` or `get_all_notams`.

2024-02-25 18:52 UTC, aidanperkins commented on notamFetch.py
> +    request_longitude_latitude expects a tuple of the form (log : float, lat : float)
For James's idea you could create a Point object from geopy with the coordinates without needing to make our own object class, or we could leave `request_longitude_latitude` as a float tuple and rename it `request_coords`.

2024-02-25 20:23 UTC, JamesJWilliams3000 commented on notamFetch.py
> +    request_longitude_latitude expects a tuple of the form (log : float, lat : float)
[Heres the geopy Point documentation](https://geopy.readthedocs.io/en/stable/index.html?highlight=point#geopy.location.Location.point). It does looks like a geopy Point object is what we need here.

2024-02-26 18:06 UTC, MinhTeeFresh reviewed
I would suggest maybe being a bit consistent about method order. From my understanding, get_notams_at utilizes 'send_api_request', which is below the method. However, the get_notams_at.register(str) utilizes get_notams_at, which is above the method. Not sure if there is a order requirement based on the functool library.

2024-02-26 18:32 UTC, Zombiepro89 commented
> I would suggest maybe being a bit consistent about method order. From my understanding, get_notams_at utilizes 'send_api_request', which is below the method. However, the get_notams_at.register(str) utilizes get_notams_at, which is above the method. Not sure if there is a order requirement based on the functool library.

Yeah, for functools library the generic function appear before the overloaded variants. But I think you're right that we should have some kind of consistent ordering. So I think i'll move send_api_request() above get_notams_at(), that way all functions appear before functions that they call. This ordering is similar to how C's scope works.

2024-02-27 00:09 UTC, aidanperkins approved these changes

2024-02-27 00:49 UTC, Zenpock approved these changes

2024-02-27 21:41 UTC, tanminivan requested changes

2024-02-27 21:41 UTC, tanminivan commented on notamFetch.py
> +    # TODO: Currently returns the union of the depature and arrival airport notams.
"TODO Currently returns the union of the departure and arrival airport notams"
Is this really a TODO or is it describing what is already done?

I understand comments like these help establish a direction/outline of what needs to happen but I think in practice they're problematic. It's too easy to leave them behind when code changes. It's also unclear when that comment should get removed, like in the case of KAN-39. Planning belongs in our planning tool, Jira. What if a comment here conflicts with what is in Jira?

I think it's fine to use this approach while you're developing—making comments that describe what some functions should do, describing in plain english or pseudocode. But it probably shouldn't make it to code review.

A (debatable) better strategy might be to stub out some of that desired functionality:

```python
def get_notams_along_path( start, end ):
    raise NotImplementedError( "Getting notams along path not yet implemented, see KAN-5" )

def get_all_notams( departure_airport, arrival_airport ):
   notams = []
   notams.append( get_notams_at( departure_airport ) )
   notams.append( get_notams_along_path( departure_airport, arrival_airport )
   notams.append( get_notams_at( arrival_airport )
   return sort_notams( notams )
```
This way, it's clear in the code what the desired form is. Downside is this will raise an exception when you try to run it. Alternatives might be for `get_notams_along_path()` to return an empty list, or a dummy list of notams: `["Dummy NOTAM 1 along path", "Dummy NOTAM 2 along path"]` if you want to have running code.

Alternatively, put the comments where that code would go so at least it's easier to clean up later:

```python
def get_all_notams( departure_airport, arrival_airport ):
   departure_airport_notams = get_notams_at( departure_airport )
   # TODO: Support getting notams along a path here (see KAN-5)
   arrival_airport_notams = get_notams_at( arrival_airport )
   # TODO: Support sorting notams here, after we've retrieved all necessary notams
   return departure_airport_notams + arrival_airport_notams
```

2024-02-27 21:41 UTC, tanminivan commented on notamFetch.py
> +geolocator = Nominatim(user_agent="notam_sort")
If this will function as a constant it should probably be stylized as such, like `GEOCODER`.

2024-02-27 21:43 UTC, tanminivan commented
Well, a push while I had some comments in review has messed up some of the line numbers and lost some of my comments. I'll try to rewrite them later today.

2024-02-27 22:34 UTC, Zombiepro89 commented on notamFetch.py
> +def _(airport_code : str) -> list:
This is similar to what we had before, but I had changed it in response to previous comments. Would it be wise to revert this overloading that we're doing to keep in-line with python syntax?

2024-02-27 22:51 UTC, tanminivan commented on notamFetch.py
> +def _(airport_code : str) -> list:
Which is easier to read and understand?

What is the goal here? Is the goal to support fetching notams for both airport codes and coordinates? or is the goal to have function overloading?

2024-02-27 22:56 UTC, tanminivan commented
I'm also curious when you plan to use airport codes vs coordinates. According to [this comment from Aiden](https://github.com/OU2024Capstone/notamSort/pull/7#discussion_r1493020318) it looks like you prefer to use coordinates over the airport codes so that you can get notams for the desired radius. Is that still true?

2024-02-27 22:57 UTC, Zombiepro89 commented on notamFetch.py
> +    # If this request fails, prompt the user and return None
I'm a little confused by both your comments here. Maybe I used the wrong term, but after this code the program prints and error, so it informs the user that their specified airport code was not found. 

As for your second, the code doesn't support it now, because we don't have any middle point computations, but I imagine if this function returns 'None' then we should signal that as something went wrong. If we get a valid input and no notams, it would probably return a blank array instead.

2024-02-27 22:57 UTC, Zombiepro89 commented on notamFetch.py
> +    # TODO: Create a more robust error system
KAN-39 didn't have a PR at the time I setup this PR, but i'll make sure to remove this comment when I update the code.

2024-02-27 22:57 UTC, Zombiepro89 commented on notamFetch.py
> +        notam_list.append(current_notam_text)
Yes, you're right. We should create a Notam object here instead of just returning the text.

2024-02-27 23:03 UTC, tanminivan commented on notamFetch.py
> +    # If this request fails, prompt the user and return None
Probably the ambiguous term of "user" here. Will the user be the person at the command line terminal or the person interacting with the web application? 

> but I imagine if this function returns 'None' then we should signal that as something went wrong

Yes, precisely, and the way you signal that something went wrong is through raising exceptions :)

2024-02-27 23:14 UTC, tanminivan commented on notamFetch.py
> +def get_notams_at(request_longitude_latitude : Point) -> list:
This is a good question, and points out that everything is a tradeoff. Personally I prefer the simplicity of using primitives, but `Point`s _are_ easier to read but do expose you to some potential downsides.

2024-02-27 23:30 UTC, tanminivan commented on notamFetch.py
> +def get_notams_at(request_longitude_latitude : Point) -> list:
I think there might be a good solution here by using a wrapper class.

2024-02-29 02:42 UTC, Zombiepro89 commented on notamFetch.py
It's just for convenience. If we ever need to change the keys for whatever reason, we just change these values instead of having to change every instance of this constant appearing.

2024-02-29 02:45 UTC, Zombiepro89 commented on notamFetch.py
> +                request_latitude_longitude = {DICT_KEY_LATITUDE: location[DICT_KEY_LATITUDE], DICT_KEY_LONGITUDE: location[DICT_KEY_LONGITUDE]}
I'm doing this just in case the 'location' dictionary has extra keys. It might be an unnecessary precaution though...? Though, we don't want to call the return statement here as the return statement at the end always occurs. So it would be a waste to add another return statement here.

2024-02-29 02:48 UTC, Zombiepro89 commented on notamFetch.py
> +            raise KeyError(f"Keys are expected to be formatted as '{DICT_KEY_LATITUDE}' and '{DICT_KEY_LONGITUDE}'")
It prints "KeyError: Keys are expected to be formatted as 'latitude' and 'longitude'.". Aside from including the dictionary's name or saying "Input dictionary's keys ...", this can't really be more clear.

2024-02-29 02:51 UTC, Zombiepro89 commented on notamFetch.py
> +def get_notams_at(location) -> list:
I was unaware of this, i'll amend this to help readability.

2024-02-29 02:53 UTC, Zombiepro89 commented on notamFetch.py
> +        request_latitude_longitude = None
Ah, good catch. I missed this line of code. It should not be there, it's a vestige of older code.

2024-02-29 05:08 UTC, aidanperkins commented on notamFetch.py
> +            raise KeyError(f"Keys are expected to be formatted as '{DICT_KEY_LATITUDE}' and '{DICT_KEY_LONGITUDE}'")
Maybe we should hint about the type associated to each key as well so the error has all the necessary information about the dictionary. 
Something like "KeyError: Dictionary keys are expected to be formatted as {'latitude' : float, 'longitude' : float}."

2024-02-29 05:27 UTC, aidanperkins commented on notamFetch.py
Python standards were pretty unclear about if dictionary keys should be constants or not, but I think we could make the later code a little neater if we drop the `DICT_KEY_` portion and it would easier to type out.

2024-02-29 05:36 UTC, aidanperkins commented on notamFetch.py
> +                request_latitude_longitude = {DICT_KEY_LATITUDE: location[DICT_KEY_LATITUDE], DICT_KEY_LONGITUDE: location[DICT_KEY_LONGITUDE]}
If we return here in the function the program wont call the return statement at the end, and as long as all the necessary keys are present with the correct types I don't really see a need to pull those into a new dictionary.

2024-02-29 17:39 UTC, tanminivan approved these changes

2024-02-29 17:39 UTC, tanminivan commented on notamFetch.py
> +        notam_list.append(current_notam_text)
Probably out of scope for this ticket, better to get this closed and work on that in a future ticket. Probably a bit of work.

2024-02-29 17:39 UTC, tanminivan commented on notamFetch.py
> +            raise RuntimeError(f"Invalid airport. {location} was not found.")
Yes, nice

2024-02-29 17:39 UTC, tanminivan commented on notamFetch.py
> +            raise KeyError(f"Keys are expected to be formatted as '{DICT_KEY_LATITUDE}' and '{DICT_KEY_LONGITUDE}'")
Yeah, that makes sense @aidanperkins

2024-02-29 17:39 UTC, tanminivan commented on notamFetch.py
> +        raise TypeError(f"Unsupported input for location {location}, expected type str or dict but got {type(location)} instead.")
I could see both ways. Sometimes having the value makes it really clear where the lines got crossed. I'd probably put it in quotes though, so it's clear where the value ends and the log message begins.

2024-02-29 17:42 UTC, tanminivan commented
Don't forget to squash and rebase.

2024-02-29 21:17 UTC, tanminivan commented
SHIP IT!

2024-02-29 21:17 UTC, aidanperkins approved these changes

2024-02-29 21:18 UTC, JamesJWilliams3000 approved these changes

2024-02-29 21:34 UTC, merged