[Kan-39] Error handling with credential files
OU2024Capstone/notamSort pull request #18
Opened 2024-02-26 19:00 UTC by MinhTeeFresh

2024-02-26 20:25 UTC, Zombiepro89 reviewed
Looks pretty good. Just a suggestion, but maybe putting all of the .env testing inside of function might help the script be more readable. I assume you would call it and it would return the credentials dictionary.

2024-02-26 23:44 UTC, aidanperkins commented on notamFetch.py
> +        sys.exit()
I would just move this error checking block inside the first one to make it a bit more readable.

2024-02-26 23:45 UTC, aidanperkins reviewed
Looks good I'd just combine the 2 error checking blocks to make it more readable.

2024-02-26 23:59 UTC, aidanperkins commented on notamFetch.py
> +
You can have multiple except catches per try block
```
try :
     do everything that could throw an exception
except FileNotFoundError as e :
     print("file not found")
except Exception as e :
     print("unknown error")
```

2024-02-27 02:51 UTC, MinhTeeFresh commented on notamFetch.py
> +
I've now condensed it all into a set of exception checks, is this what you meant? (3rd commit)

2024-02-27 02:53 UTC, MinhTeeFresh commented
> Looks pretty good. Just a suggestion, but maybe putting all of the .env testing inside of function might help the script be more readable. I assume you would call it and it would return the credentials dictionary.

I could add it to its own function, but that would mean we would have to call it before running any other script. It should be only ran one time though, so I'm not sure we need it in a function to be recalled? Not sure if that covers what you were implying.

2024-02-27 17:19 UTC, tanminivan requested changes

2024-02-27 17:19 UTC, tanminivan commented on notamFetch.py
> +        raise ValueError("Client ID or Client Secret is empty in '.env' file")
I'm not sure if `ValueError` is really the best Exception to use:

> exception ValueError[¶](https://docs.python.org/3/library/exceptions.html#ValueError)
>
> Raised when an operation or function receives an argument that has the right type but an inappropriate value, and the situation is not described by a more precise exception such as [IndexError](https://docs.python.org/3/library/exceptions.html#IndexError).

It's not that we have the right type/bad value but that we have _no_ value. I think `RuntimeException` might be a better choice.

2024-02-27 17:19 UTC, tanminivan commented on notamFetch.py
> +    sys.exit()
I'm not really a fan of handling errors like this.

First, you're calling `sys.exit()` which is the same as `sys.exit(0)` which is going to exit with a 0 return code which tells the OS that the program ended normally. But that's not the case here! We ended _abnormally_! So `sys.exit(1)` would have been a better choice.

Second, printing the exception with just "Error:" doesn't really give any context to what is going on. Maybe better wording would be `Error on initialization` or including some more context `Error while reading FAA API Authorization credentials` or something similar. You _know_ it's an error because you can see the stack trace. Give some more context.

But really, exiting _at all_ is problematic. Does this leave our frontend running without a backend? Does this exception have a chance to bubble up where someone could see it? Or is there just a silent error and suddenly no running process, requiring someone to dig into logs to see what happened? Remember that Exceptions are for handling _Exceptional_ cases! Something is wrong! Our program can't run like this! Someone must know! Raise that exception! Let it go where it needs to! If nothing handles it, python itself will exit if it has to.

Now, there can be an argument made about raising exceptions can leak internals to end users.  But I don't think we're at the point yet where we need to be concerned about that.

Does that make sense?

2024-02-27 17:19 UTC, tanminivan commented on notamFetch.py
> +    credentials = {
This is functioning as a constant at this point and should probably be stylized as such according to PEP 8: `CREDENTIALS`. Even better would be a more descriptive name.

2024-02-27 20:08 UTC, MinhTeeFresh commented on notamFetch.py
> +    sys.exit()
Hm, I understand the concerns of exiting. I didn't think about how the sys.exit() would affect the front end. I intended to utilize the the exit because despite raising exceptions, the program would still attempt to run the program without credentials. This would point the error to later in the code as something along the lines of "attempted to utilize 'credentials' before assigning a value". I was attempting to end the program before that point, as the backend wouldn't run anyways without our Auth credentials.

2024-02-27 20:19 UTC, tanminivan commented on notamFetch.py
> +    sys.exit()
> I intended to utilize the the exit because despite raising exceptions, the program would still attempt to run the program without credentials. 

This is an even bigger program. You are encountering Exceptional cases but the program is running anyways? That seems dangerous. How are you running this?

2024-02-27 21:44 UTC, MinhTeeFresh commented on notamFetch.py
> +    sys.exit()
From my understanding raising exceptions and catching them in except blocks doesn't end the program in python?? So (for temporary testing purposes) I am running `print_to_console(get_notams('JFK', 'OKC'))` at the end of the script. So when the program runs, it continues to "get_notams" but of course ends process at the API call itself because the credentials aren't declared. But the program itself doesn't stop until that point is what I mean. Clarification: the program will stop eventually, it just doesn't stop as soon as the exception is raised, because it is caught in the exception blocks (this is if used without the exiting) and I am calling get_notams. Unless I am wrong in my understanding of the except blocks.

2024-02-27 21:55 UTC, tanminivan commented on notamFetch.py
> +    sys.exit()
And what happens if you _don't_ catch the exception?

2024-02-28 15:54 UTC, MinhTeeFresh commented on notamFetch.py
> +    sys.exit()
Part of the error handling was handled within the method, so part of the credential retrieval would have been completed every time the method was called. Is that possibly the other reason for combining it outside the method?

2024-02-28 16:04 UTC, tanminivan approved these changes

2024-02-28 16:14 UTC, tanminivan commented on notamFetch.py
> +    sys.exit()
Discussed this offline a bit and I wanted to follow up here for everyone's benefit. 

Handling an exception by exiting the program is _technically_ handling an exception, but it's not really the best way. Think about like this: It's the end of the semester and you are demoing your application to the professor. He inputs something you don't expect, your application raises an exception, catches it, then the program exits. Is that the behavior that you want? Probably not.

A better way is to throw the exception. Something else will handle it... one day. But not today. We're focused on just fetching notams. To fetch notams, we know we need a few things like valid credentials and a working API. If we don't have that, we must throw an exception. If there's no credentials, there's nothing that we can do _in code_ to get the notams that we want.

Later, we'll likely handle those exceptions by making sure we display a helpful error message to the user via the web interface, but that's out of the scope of this ticket.

2024-02-28 16:25 UTC, tanminivan commented on notamFetch.py
> +    sys.exit()
Yes, exactly. If you don't have credentials specified, would you rather throw an exception on application startup or when it tries to process the first request?

2024-02-28 19:34 UTC, MinhTeeFresh commented on notamFetch.py
> +    sys.exit()
I believe on application startup would be more ideal

2024-02-28 19:59 UTC, Zombiepro89 approved these changes

2024-02-29 01:01 UTC, Zenpock approved these changes

2024-02-29 05:00 UTC, aidanperkins approved these changes

2024-02-29 06:18 UTC, merged