[KAN-5] Implemented middle notam searching and added helper functions for it.
OU2024Capstone/notamSort pull request #19
Opened 2024-02-29 22:34 UTC by aidanperkins

Added `get_notams_between`, `get_distance`, `get_bearing`, `get_next_point`, and an alternative to the geoPy implementation for finding the next point a given distance and bearing away from a point `get_next_point_by_coords`. These functions can take the string given by the user, dictionaries of latitudes and longitudes, or the individual longitudes and latitudes as parameters.

2024-03-01 19:37 UTC, Zombiepro89 requested changes
Looks good for the most part, mostly just comments about structure and possibly removing our reliance on functools. I say we could use tuples, but it might wise to just create dictionaries instead that way, when we only have the lat/long, we only need to handle 2 cases instead of 3.

2024-03-01 19:37 UTC, Zombiepro89 commented on notamFetch.py
> +        )
I am not a fan of this function call structure, it's difficult to read. Having it one line would be easier to read.

2024-03-01 19:37 UTC, Zombiepro89 commented on notamFetch.py
> +                 point_two_latitude: float, point_two_longitude: float) -> float :
Overloading this function seems unnecessary. You could accomplish a similar task by asking for either 2 tuples (lat, long), 2 dictionaries, or 2 strings. Maybe combine the 3 functions into a single function and handle each case with if statements?

2024-03-01 19:37 UTC, Zombiepro89 commented on notamFetch.py
> +                 latitude_two: float, longitude_two: float) -> float :
Again, maybe consider combining the 3 functions by accepting either 2 tuples, 2 dictionaries, or 2 strings.

2024-03-01 19:37 UTC, Zombiepro89 commented on notamFetch.py
> +    latitude_difference_radians = abs(latitude_difference_radians)
You could condense these two lines down to one line and it shouldn't affect readability.

2024-03-01 19:37 UTC, Zombiepro89 commented on notamFetch.py
> +        * math.cos(latitude_difference_radians)))
Again, I find this structure difficult to read. It might be easier if you were to condense it down into a few line like so:
```
y = ( (math.cos(longitude_one_radians) * math.sin(latitude_difference_radians)) 
      - (math.cos(longitude_one_radians) * math.cos(longitude_one_radians * math.cos(latitiude_difference_radians))) )
```

2024-03-01 19:37 UTC, Zombiepro89 commented on notamFetch.py
> +def get_next_point(latitude: float, longitude: float, bearing: float, distance: float) -> dict :
Again, we could avoid overloading by asking for either a tuple, dictionary, or str in addition to the bearing and distance.

2024-03-01 19:37 UTC, Zombiepro89 commented on notamFetch.py
> +    )
This is especially hard to read, the two arguments for atan2 are difficult to see. Consider computing atan2's arguments before hand.

2024-03-01 19:37 UTC, Zombiepro89 commented on notamFetch.py
> +                       spacing: float) -> list :
I know I sound like a broken record, but we can remove these overloaded functions by asking for either 2 tuples, 2 dictionaries, or 2 strings in addition to the spacing argument.

2024-03-01 19:38 UTC, Zombiepro89 commented
Okay, seems like you resolved some of the issues I had as I was typing them, i'll resolve those now.

2024-03-02 02:31 UTC, MinhTeeFresh requested changes
Just a few suggestions maybe that I'd like to see your thoughts on.

2024-03-02 02:31 UTC, MinhTeeFresh commented on notamFetch.py
> +            raise ValueError(f"Error: point_two is of the wrong type, excepted str or dict and got {type(point_one)}")
I think you were attempting to point out the type inputted in point_two? The message is currently checking point_one. 

Also, a little nitpick, is the message saying "accepted types are str or dict and instead got {type(point_two)}" or am I just misinterpreting this message? 

Kind of connected to what I said above, if point one is one type (dict or str) and the other point is the other type, then this message isn't as clear that the problem could be that they have to be of the same type.

2024-03-02 02:31 UTC, MinhTeeFresh commented on notamFetch.py
> +            raise ValueError(f"Error: points are of the wrong type, excepted str or dict and got {type(point_one)} and {type(point_two)}")
A lot of this part is very similar to the checks within get_distance, I know its not exactly the same but is there a way we can condense this, that way we don't have repetitive code?

2024-03-02 02:31 UTC, MinhTeeFresh commented on notamFetch.py
> +        raise ValueError(f"Error: point is of the wrong type, excepted str or dict and got {type(point)}")
Hmm again not sure if it is easier to have it separated for its purposes in each method, but this is also very similar to a portion in the get_next_point.

2024-03-02 02:31 UTC, MinhTeeFresh commented on notamFetch.py
> +            raise ValueError(f"Error: points are of the wrong type, excepted str or dict and got {type(point_one)} and {type(point_two)}")
Just the same stuff I said above, but in this case we have additional cases that take care of if they are two different 'acceptable' types (ie str and dict or dict and str). So this error message makes a bit more sense in this context.

2024-03-02 07:56 UTC, aidanperkins commented on notamFetch.py
> +            raise ValueError(f"Error: point_two is of the wrong type, excepted str or dict and got {type(point_one)}")
Yeah, I was rushing through the type checking earlier I've improved it a bit now.

2024-03-02 15:54 UTC, Zombiepro89 approved these changes

2024-03-02 17:36 UTC, tanminivan requested changes
I didn't make it all the way through this before I had to leave, but I wanted to go ahead and post these comments. I'll try to review the remainder later.

2024-03-02 17:36 UTC, tanminivan commented on notamFetch.py
It feels like we're getting focused and specialized enough from just fetching Notams that much of this code should be split off into its own class.

2024-03-02 17:36 UTC, tanminivan commented on notamFetch.py
> +# radius of the earth in nautical miles
including units, nice

2024-03-02 17:36 UTC, tanminivan commented on notamFetch.py
> +NOTAM_SPACING = 40
Probably call this `DEFAULT_NOTAM_SPACING` since this is the default, but could be changed.

`NOTAM_SPACING` makes sense in the context of the ticket, but just taken alone it could be perplexing ("wait, notams have spacing? is this about whitespace or physical space?"). What about something like `DEFAULT_PATH_STEP_SIZE_IN_NM`?

2024-03-02 17:36 UTC, tanminivan commented on notamFetch.py
> +# doesnt work if the notam list isnt built
Could just remove this comment and add at the beginning of the `save_to_file()`:

```python
if not full_notam_list:
    print( "No notams fetched yet" )
    return
```

2024-03-02 17:36 UTC, tanminivan commented on notamFetch.py
> +        # we need to convert our string input to a set of coordinates
"we need to convert our string input (likely an airport code, like KOKC) to a set of coordinates"

2024-03-02 17:36 UTC, tanminivan commented on notamFetch.py
> +    if (isinstance(point_two, dict)) :
Code duplication, let's extract this into its own method so that we don't have to repeat ourselves, and we also don't have to ensure if we make changes to this in the future, we have to make it in two places.

2024-03-02 17:36 UTC, tanminivan commented on notamFetch.py
> +        raise ValueError(error_message)
nice

2024-03-02 17:36 UTC, tanminivan commented on notamFetch.py
> +        * math.cos(latitude_difference_radians)))
I'd defer to the pep8 standards. And unfortunately, with some of this math it's just going to be ugly no matter what.

My only suggestion is that if you can break this down further into named components, it might be a little bit easier to follow.

An example might be, instead of something like:

```python
result = ( ( x1 + x2 + x3 ) / (y1 + y2 + y3 ) )
```

You do this instead:
```python
numerator = x1 + x2 + x3
denominator = y1 + y2 + y3
result = numerator / denominator
```

It's technically redundant, but does make it easier to read and possibly spot bugs.

2024-03-03 03:14 UTC, tanminivan requested changes

2024-03-03 03:14 UTC, tanminivan commented on notamFetch.py
> +    spacing = geopy.distance.distance(miles=distance*NM_TO_MILES)
When I run this, I get an error:
```
AttributeError: module 'geopy' has no attribute 'distance'
```
I have geopy 2.4.1, am I missing something?

2024-03-03 03:14 UTC, tanminivan commented on notamFetch.py
> +def get_notams_between(point_one: dict | str, point_two: dict | str, spacing: float) -> list :
`get_notams_between` looks like it's only ever called with airport codes, what is the benefit of supporting dicts here?

2024-03-04 17:31 UTC, aidanperkins commented on notamFetch.py
> +    spacing = geopy.distance.distance(miles=distance*NM_TO_MILES)
I forgot a `.distance` in the imports. Fixed now.

2024-03-04 18:12 UTC, JamesJWilliams3000 approved these changes

2024-03-04 22:03 UTC, tanminivan commented on NavigationTools.py
> +class Point :
Is this class name going to conflict with geopy's `Point` class?

2024-03-04 22:53 UTC, aidanperkins commented on NavigationTools.py
> +class Point :
Only if we specifically include `from geopy import Point` at the top of notamFetch.py as well. Would it be better to rename it something like `CustomPoint` or `PointObject`?

2024-03-04 22:59 UTC, tanminivan commented on NavigationTools.py
> +class Point :
I think that would likely be best to avoid confusion

2024-03-05 01:18 UTC, tanminivan approved these changes

2024-03-05 01:18 UTC, tanminivan commented on NavigationTools.py
> +    if not(isinstance(point_one, PointObject)) :
You know, now I'm curious about python. With type hinting, does it even make it this far or does python raise an error as soon as you try to call this function with non-`PointObject`s?

2024-03-05 01:18 UTC, tanminivan commented on NavigationTools.py
> +    longitude: float value between -180 and 180
between and including these values?

2024-03-05 01:18 UTC, tanminivan commented on NavigationTools.py
> +    def from_string(cls, location = None) :
Would `from_airport_code()` be a little more precise? I get that you can use an address so you want to keep it general but I think for our use case, we'll only be using it for airport codes.

2024-03-05 03:50 UTC, aidanperkins commented on NavigationTools.py
> +    if not(isinstance(point_one, PointObject)) :
I have not used type hinting a lot before this project but I found out in the docs it never actually checks the parameter type. So it ends up just being for documentation sake and never throws an error on its own. There are actually some tools that scan your file and check the the types but we're not using any.

2024-03-05 03:51 UTC, aidanperkins commented on NavigationTools.py
> +    def from_string(cls, location = None) :
That's true, especially now that airport codes are strictly required by the program.

2024-03-05 04:26 UTC, tanminivan commented on NavigationTools.py
> +    if not(isinstance(point_one, PointObject)) :
Makes sense.

2024-03-05 16:03 UTC, Zombiepro89 approved these changes

2024-03-05 16:26 UTC, Zenpock approved these changes

2024-03-05 17:03 UTC, MinhTeeFresh approved these changes

2024-03-05 17:03 UTC, merged