[KAN-44] notamFetch now returns a list of Notam objects
OU2024Capstone/notamSort pull request #20
Opened 2024-03-01 00:08 UTC by JamesJWilliams3000

To make object creation easier, Notam.py now has:
1. Two `__init__`, one with the priority variable and one without
2. `__str__` for printing notams in an easy-to-read format
3. A list of constants referring to the property names in the faa api. Now we can use `.get(Notam.EFFECTIVE_START)` in lieu of `.get('effectiveStart')`

In notamFetch.py:
1. send_api_request now returns list of notam objects, rather than a list of 'text' strings.

2024-03-01 18:58 UTC, Zombiepro89 requested changes
Looks good, just a few changes that i'd like to see. Also, I really like the constants inside the Notam object to access API output, that's clever.

2024-03-02 02:04 UTC, MinhTeeFresh approved these changes

2024-03-02 17:08 UTC, tanminivan requested changes

2024-03-02 17:08 UTC, tanminivan commented on Notam.py
> +    priority = 0 #used for sorting
Since this notam object is adapted from data from the API, it might be a good idea to distinguish between class variables that come from the API and variables that are for our own internal use, like `priority`.

2024-03-02 17:08 UTC, tanminivan commented on Notam.py
> +            s+= '{0}: {1}\n'.format(item, temp[item])
Prefer f-strings in python3:
```
s += f"{item}: {temp[item]}\n"
```

(Effective Python, second edition, Item 4: Prefer interpolated f-strings over C-style format strings and `str.format` :upside_down_face: )

2024-03-03 02:51 UTC, tanminivan approved these changes

2024-03-03 03:13 UTC, Zombiepro89 approved these changes

2024-03-03 03:13 UTC, Zombiepro89 commented on Notam.py
> +    def __init__(self, raw_notam_data):
Make sure to add the typing hints so it's easier to tell what kind of input the function is expecting.

2024-03-03 16:23 UTC, Zenpock approved these changes

2024-03-03 16:55 UTC, merged