[KAN-48] Implemented method to validate airport codes
OU2024Capstone/notamSort pull request #22
Opened 2024-03-03 09:10 UTC by JamesJWilliams3000

- I figured out how to use Nominatim to validate US airport codes
- Frontend now has the function `valid_US_airport_code`; once displaying error messages to the user through Flask is implemented, `valid_US_airport_code` will be called before calling `notamFetch`
- I also made `test_validation_with_input` just to test the validation code with the current Flask form; it will vanish once displaying error messages are implemented.

2024-03-03 16:35 UTC, Zombiepro89 requested changes

2024-03-03 16:35 UTC, Zombiepro89 commented on app.py
> +
I like the documentation, but remember that you can also tell the user more directly what the arguments are expected to be and the return values by doing: `def valid_US_airport_code(user_input : str) -> bool:`

2024-03-03 16:35 UTC, Zombiepro89 commented on app.py
> +
Some airport codes are not 3 characters long, [refer to the website Brian sent](https://adds-faa.opendata.arcgis.com/datasets/faa::airports-1/explore).

2024-03-03 16:35 UTC, Zombiepro89 commented on app.py
> +    message=""
Type hinting?

2024-03-04 02:40 UTC, tanminivan commented on app.py
> +def valid_US_airport_code(user_input):
For boolean responses, I like method names like `is_valid_US_airport_code()` because it reads much easier in code:

```python
if is_valid_US_airport_code( input )
    ...
```

2024-03-04 02:40 UTC, tanminivan commented on app.py
> +    user_input = user_input.upper()
Would prefer to not redefine variables, you could just inline this in the next line:

```
geocode_query = f"{user_input.upper()} Airport"
```

2024-03-04 02:40 UTC, tanminivan commented on app.py
> +        airport = next(filter(lambda location:
What if there is more than one result? Are we certain we're getting the right one?

2024-03-04 02:40 UTC, tanminivan commented on app.py
> +                            location.raw.get('class') =='aeroway' and
Doing filtering on the results is kinda odd. Is there not a way to include the aeroway class filter in the query itself?

2024-03-04 02:40 UTC, tanminivan commented on app.py
> +    geocoder_results = GEOLOCATOR.geocode(geocode_query, exactly_one=False, namedetails=True, country_codes="US" )
More geocoder usage, but no error handling if the service is unvailable.

2024-03-04 02:40 UTC, tanminivan commented on app.py
> +def valid_US_airport_code(user_input):
I question if we should be pushing so much business logic to the frontend instead of the backend. What's your reasoning for including it here?

2024-03-04 02:40 UTC, tanminivan commented on app.py
> +    # Airport code must be 3 characters long.
This is a good time to drop https://www.youtube.com/watch?v=jfOUVYQnuhw

2024-03-04 02:40 UTC, tanminivan commented on app.py
> +# so I've put this here to test validate_airport_codes with user input.
Leave a note to KAN-47 which I think would be the ticket handling that functionality?

2024-03-04 02:40 UTC, tanminivan commented on app.py
> +                            location.raw.get('namedetails').get('iata') == user_input,
Reading more about this, I think you'll definitely want ICAO instead of IATA.

2024-03-04 18:18 UTC, JamesJWilliams3000 commented on app.py
> +    user_input = user_input.upper()
I actually did this originally, but it didn't seem to work. I'll look at it again. (Hoping I didn't do something like put .upper() OUTSIDE the curly brackets....)

2024-03-04 18:25 UTC, JamesJWilliams3000 commented on app.py
> +                            location.raw.get('class') =='aeroway' and
I tried to include it in the query, but Nominatim seems to take categories as 'suggestions' rather than a hard filter (unlike country codes, which will only give locations from that country). I perused the Nominatim github repo, and one of the devs mentions this, as well as mentioning that they have no intention of prioritizing airport codes after a few people asked about it; currently the order that locations are returned has something to do with their wikipedia pages(?)

2024-03-04 20:16 UTC, JamesJWilliams3000 commented on app.py
> +    user_input = user_input.upper()
Ok, I figured out why it didn't work originally. When comparing the geocoder results to the user input, I was using a case-sensitive string comparison.

2024-03-04 23:02 UTC, Zombiepro89 requested changes

2024-03-04 23:02 UTC, Zombiepro89 commented on notamFetch.py
> +        geocoder_results = GEOLOCATOR.geocode(geocode_query, exactly_one=False, namedetails=True, country_codes="US" )
You should define this prior, just in case the geocode function fails. If it fails, geocoder_results is left undefined.

2024-03-04 23:09 UTC, tanminivan commented on notamFetch.py
> +def is_valid_US_airport_code(user_input : str) -> bool:
Why is this in notamFetch.py? does it have to do with fetching notams?

2024-03-04 23:09 UTC, tanminivan commented on notamFetch.py
> +    if(len(user_input) != 4):
So I can't use `OKC` anymore?

2024-03-10 17:24 UTC, aidanperkins approved these changes

2024-03-10 17:25 UTC, aidanperkins commented on notamFetch.py
> +
We can catch this error in the front end and display the error message there if we dont catch it back here. Right now the app would just continue to run with geopy down instead.

2024-03-10 21:41 UTC, SirFlarflajon commented on notamFetch.py
> +    if(len(user_input) != 4):
Just wondering if there will be any implementation to allow IATA as well. I have heard we are and are not using it.

2024-03-11 17:55 UTC, MinhTeeFresh approved these changes

2024-03-11 21:49 UTC, merged