[KAN-51] fixed a couple bugs with expecting floats instead of ints and list concatenation
OU2024Capstone/notamSort pull request #24
Opened 2024-03-05 22:41 UTC by aidanperkins

Our error checking was a bit too strict. Usually the `int`s would have just been cast to a `float` but we were throwing errors. There was also an issue where I was creating a list of lists (Cory called it) instead of a single list.

2024-03-05 23:09 UTC, SirFlarflajon approved these changes

2024-03-05 23:16 UTC, Zombiepro89 requested changes
Please fix update Brian's unit test file so that it functions and add a `__str__` function to PointObject so we can see the latitude and longitude of the point.

You can fix Brian's file by changing line 15 to `COORIDINATES = NavigationTools.PointObject(35.0, -95.0)`
and then changing all occurrences of `notamFetch.send_api_request()` -> `notamFetch.get_notams_at()`

2024-03-06 20:54 UTC, JamesJWilliams3000 approved these changes

2024-03-06 22:31 UTC, merged

2024-03-07 00:03 UTC, tanminivan commented
Why didn't you squash and rebase? :cry:

2024-03-07 00:05 UTC, tanminivan commented
> Why didn't you squash and rebase? 😢
Ah nevermind, I was misreading the logs