[KAN 42] Create Unit Tests
OU2024Capstone/notamSort pull request #27
Opened 2024-03-10 02:33 UTC by SirFlarflajon

Added a unit test file for check various inputs. When we get more exceptions and features dealing with inputs I will need to revisit the file to add/edit some tests.

2024-03-10 17:27 UTC, aidanperkins approved these changes

2024-03-10 17:27 UTC, aidanperkins commented on tests/notamTests.py
> +        print("Testing inputs with airport codes:")
shouldnt we test with ICAO airport codes?

2024-03-10 21:29 UTC, SirFlarflajon commented on tests/notamTests.py
> +        print("Testing inputs with airport codes:")
I heard we were using ICAO and IATA so I put in one for now, I can add that to the lists of tests to include though.

2024-03-10 21:54 UTC, aidanperkins approved these changes

2024-03-10 23:04 UTC, Zombiepro89 approved these changes

2024-03-11 04:23 UTC, Zenpock approved these changes

2024-03-11 18:17 UTC, tanminivan commented on tests/notamTests.py
> +    def test_canada_mexico(self):
Does this still need to be here if you have the above tests?

2024-03-11 18:17 UTC, tanminivan commented on tests/notamTests.py
> +    def test_alaska(self) :
Would prefer if this was something like `test_alaska_fails` so it's clear from the name what the expected outcome is

2024-03-11 18:17 UTC, tanminivan commented on tests/notamTests.py
> +            self.fail("Airport was not located when it should have been.")
Is this always true when we catch `Exception`?

2024-03-11 20:06 UTC, SirFlarflajon commented on tests/notamTests.py
> +    def test_canada_mexico(self):
I actually meant to delete this one and it just slipped my mind

2024-03-11 20:12 UTC, SirFlarflajon commented on tests/notamTests.py
> +    def test_inputs_valid_ICAO(self):
The goal with this test is that if I give the method two ICAO codes, both will get notams. I may need to look at the exception more though.

2024-03-11 22:09 UTC, JamesJWilliams3000 requested changes

2024-03-11 22:09 UTC, JamesJWilliams3000 commented on tests/notamTests.py
> +    def test_inputs_valid_ICAO(self):
Looking more at this, if you are testing specifically that the input is valid, I don't think calling `get_notams_at` will tell you this. Especially since it seems we're testing for the existence of a notam list, and not that the contents of the list are correct. The fact that there are notams returned simply means that the input was converted to some coordinate value in the US, it may not be the coordinates of the airports in question. I'm probably repeating myself, but you'll want to look at the returned coordinates if you're validating input.

2024-03-11 22:15 UTC, JamesJWilliams3000 commented on tests/notamTests.py
> +            self.fail("Airport was not located when it should have been.")
You may want to specifically check for the `ValueError` exception, otherwise if any of the `RuntimeError` exceptions are raised, the test will fail when it shouldn't.

2024-04-02 19:32 UTC, Zenpock approved these changes

2024-04-02 19:59 UTC, JamesJWilliams3000 approved these changes

2024-04-02 19:59 UTC, aidanperkins approved these changes

2024-04-04 15:16 UTC, tanminivan requested changes

2024-04-04 15:16 UTC, tanminivan commented on tests/notamTests.py
> +    # Test should fail given a code with too few characters.
Group similar tests together. Everything that tests `is_valid_US_airport_code()` together in this file, everything that tests `get_notams_at()` should be together, etc.

2024-04-04 15:16 UTC, tanminivan commented on tests/notamTests.py
> +    @unittest.skip("get_all_notams takes awhile to run as of now.")
nice use of skip

2024-04-04 15:16 UTC, tanminivan commented on tests/notamTests.py
> +            self.fail("Airport was not located when it should have been.")
Is this error message always true? What if the exception raised was for a different reason, like say the API was unavailable. Would this message be misleading?

2024-04-04 15:16 UTC, tanminivan commented on tests/notamTests.py
> +        print("Testing " + airport + ":")
Use f-strings, like `f"Testing {airport}:"`

Effective Python #4

2024-04-04 15:16 UTC, tanminivan commented on tests/notamTests.py
When I run this, I get some weird formatting:

```
Testing PAJN:
.Testing CYOW:
.ssTesting EDDB:
.Testing PHNL:
.Testing inputs fewer than 3:
ETesting float decimal inputs:
.Testing integer inputs:
.Testing inputs greater than 4:
ETesting no inputs:
.Testing IATA airport code input:
ETesting ICAO airport code input:
ETesting MMMX:
```
What is going on with these Es and periods?

2024-04-04 15:16 UTC, tanminivan commented on tests/notamTests.py
Why are these tests failing?

```
======================================================================
ERROR: test_inputs_invalid_few_char (tests.notamTests.TestNotams)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brian/git/notamSort/tests/notamTests.py", line 39, in test_inputs_invalid_few_char
    self.assertFalse(notamFetch.is_valid_US_airport_code(airport, msg))
AttributeError: module 'notamFetch' has no attribute 'is_valid_US_airport_code'

======================================================================
ERROR: test_inputs_invalid_many_char (tests.notamTests.TestNotams)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brian/git/notamSort/tests/notamTests.py", line 46, in test_inputs_invalid_many_char
    self.assertFalse(notamFetch.is_valid_US_airport_code(airport, msg))
AttributeError: module 'notamFetch' has no attribute 'is_valid_US_airport_code'

======================================================================
ERROR: test_inputs_valid_IATA (tests.notamTests.TestNotams)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brian/git/notamSort/tests/notamTests.py", line 16, in test_inputs_valid_IATA
    self.assertTrue(notamFetch.is_valid_US_airport_code(airport), msg)
AttributeError: module 'notamFetch' has no attribute 'is_valid_US_airport_code'

======================================================================
ERROR: test_inputs_valid_ICAO (tests.notamTests.TestNotams)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brian/git/notamSort/tests/notamTests.py", line 23, in test_inputs_valid_ICAO
    self.assertTrue(notamFetch.is_valid_US_airport_code(airport), msg)
AttributeError: module 'notamFetch' has no attribute 'is_valid_US_airport_code'

----------------------------------------------------------------------
Ran 14 tests in 0.001s
```

2024-04-04 15:16 UTC, tanminivan commented on tests/notamTests.py
> +        with self.assertRaises(Exception):
Not a change I'm requesting for this PR, but what is the danger of ensuring `Exception` is raised rather than a more specific exception?

2024-04-04 18:28 UTC, SirFlarflajon commented on tests/notamTests.py
Those won't work until I merge to main as I do not have the is_valid_US_airport_code method in notamFetch on my branch.

2024-04-04 18:31 UTC, SirFlarflajon commented on tests/notamTests.py
I just looked it up, apparently that might be Python returning the test result. Not sure why the "ss" is there but '.' and 'E' seem to be common

2024-04-04 18:32 UTC, SirFlarflajon commented on tests/notamTests.py
> +        print("Testing " + airport + ":")
I forgot that was a thing let me change that

2024-04-04 18:36 UTC, SirFlarflajon commented on tests/notamTests.py
> +        print("Testing IATA airport code input:")
Not quite sure I understand what you mean by this one.

2024-04-04 18:37 UTC, SirFlarflajon commented on tests/notamTests.py
> +        msg = "The input was not detected as valid."
I can change it to that, I just tend to set the variables up beforehand.

2024-04-04 18:49 UTC, SirFlarflajon commented on tests/notamTests.py
> +    # Test invalid inputs in the frontend
That was just a small grammar mistake on my end, that's just meant to be a comment for the invalid input section of tests

2024-04-04 19:09 UTC, tanminivan commented on tests/notamTests.py
Don't merge to main first, rebase off of main to pick up that change

2024-04-04 19:11 UTC, tanminivan commented on tests/notamTests.py
> +        print("Testing IATA airport code input:")
You never log the airport that you use for testing

2024-04-04 20:02 UTC, SirFlarflajon commented on tests/notamTests.py
> +        print("Testing IATA airport code input:")
Oh do you mean in the print statement?

2024-04-04 20:04 UTC, SirFlarflajon commented on tests/notamTests.py
Okay so what I've found out is that '.' means "ok", 'E' means "ERROR" and 's' means "SKIP"
What I don't know is how to ignore these outputs for now, otherwise I do believe they are harmless in terms of testing

2024-04-04 20:13 UTC, tanminivan commented on tests/notamTests.py
> +        print("Testing IATA airport code input:")
Yes

2024-04-04 20:13 UTC, tanminivan commented on tests/notamTests.py
Interesting, TIL

2024-04-10 02:55 UTC, tanminivan commented on tests/notamTests.py
It still doesn't look like this has been rebased to pick up those changes.

2024-04-10 02:55 UTC, tanminivan commented on tests/notamTests.py
Let me know if you need help with that.

2024-04-10 02:58 UTC, tanminivan commented on tests/notamTests.py
Let's also be sure to squash these commits into one.

2024-04-11 17:12 UTC, SirFlarflajon commented on tests/notamTests.py
> +        print("Testing IATA airport code input:")
Should be added now!

2024-04-11 17:14 UTC, SirFlarflajon commented on tests/notamTests.py
> +    # Test should fail given a code with too few characters.
I believe they should be regrouped in a better order now

2024-04-11 18:54 UTC, Zombiepro89 approved these changes

2024-04-11 19:09 UTC, tanminivan commented on tests/notamTests.py
> +        print("Testing IATA airport code input:")
I'm still seeing no change here.

I see this line:
```python
print("Testing IATA airport code input:")
```

I'm expecting something like this:
```python
print( f"Testing IATA airport code input: {airport} ")
```

Github is set to show me all my commits:

![image](https://github.com/OU2024Capstone/notamSort/assets/593822/a3681bce-6975-45c2-b770-c039d9a1423e)

Am I missing something here?

2024-04-11 19:13 UTC, tanminivan commented on tests/notamTests.py
> +    # Test should fail given a code with too few characters.
I still see `is_valid_US_airport_code()` tests on lines 79-97

2024-04-11 19:16 UTC, tanminivan commented
This commit history looks very suspect. I see multiple merges from this branch into itself, which is indicative of rebases gone wrong. Are we sure that we can squash all of these commits into one before merging?

2024-04-11 19:20 UTC, tanminivan commented on tests/notamTests.py
I'm running this again from this commit: ba648265e9f51cc570add780037ebac612b24ee3

I still see an error:

```
$ python3 -m unittest tests/notamTests.py
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/usr/lib/python3.8/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.8/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/usr/lib/python3.8/unittest/main.py", line 158, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
  File "/usr/lib/python3.8/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.8/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/bschettl/git/notamSort/tests/notamTests.py", line 2, in <module>
    import notamFetch
  File "/home/bschettl/git/notamSort/notamFetch.py", line 9, in <module>
    from NavigationTools import *
  File "/home/bschettl/git/notamSort/NavigationTools.py", line 133, in <module>
    def get_next_point_geopy(point: PointObject, bearing: float, distance: float| int) -> PointObject :
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

Is this a new issue? Or an issue from a bad rebase?

2024-04-11 22:09 UTC, tanminivan approved these changes

2024-04-11 22:09 UTC, merged