[KAN 38] (EH) geoLocator web call
OU2024Capstone/notamSort pull request #28
Opened 2024-03-11 19:54 UTC by SirFlarflajon

Added some exception catching to the .geocode calls used inside of NavigationTools. I did not add every error as of now as looking into them, some of them felt unnecessary given what we were using. I did add the two generic exception calls in case there are any additional errors caught.

I also removed any usage of geopy in notamFetch as all of that gets handled in NavigationTools.

2024-03-11 23:41 UTC, aidanperkins commented on NavigationTools.py
>          if not(isinstance(longitude, (float, int))) :
If we handle these differently we should raise the error between them instead of adding all 4 error messages to the log.

2024-03-11 23:44 UTC, aidanperkins commented on NavigationTools.py
> +                error_var = GeocoderQueryError("Error: Connection with the geocoding service timed out")
Shouldn't this be `GeocoderTimedOut`?

2024-03-11 23:57 UTC, aidanperkins requested changes

2024-03-11 23:57 UTC, aidanperkins commented on NavigationTools.py
>          if not(isinstance(longitude, (float, int))) :
If we handle these differently we should raise the error between them or use elifs instead of adding all 4 error messages to the log.

2024-03-11 23:57 UTC, aidanperkins commented on NavigationTools.py
> +                error_var = GeocoderQueryError("Error: Connection with the geocoding service timed out")
Shouldn't this be `GeocoderTimedOut`?

2024-03-11 23:57 UTC, aidanperkins commented on NavigationTools.py
> +            except GeocoderQueryError as e :
We already do type-checking to make sure we're given a string, does this exception ever get thrown?

2024-03-11 23:57 UTC, aidanperkins commented on NavigationTools.py
> +                error_var = GeopyError(f"Error: Geocode failed on {location} with error message {e}")
The exceptions `GeocoderUnavailable`, `GeocoderTimedOut`, and `GeocoderServiceError` seem similar enough we could throw the same error message for all of them, I don't think we have to distinguish between them.

2024-03-11 23:57 UTC, aidanperkins commented on NavigationTools.py
> +                location_geocode = GEOLOCATOR.geocode(location)
I believe `GEOLOCATOR.geocode()` does not throw an exception when it can't find a result it just returns `None`, but I dont see that we check for that.

2024-03-11 23:57 UTC, aidanperkins commented on NavigationTools.py
>          location: a string (KOKC airport code or address) to convert to a set of coordinates
IATA or ICAO airport code?

2024-03-26 18:31 UTC, Zenpock commented on NavigationTools.py
>          location: a string (KOKC airport code or address) to convert to a set of coordinates
Both IATA and ICAO can be used now

2024-04-04 15:41 UTC, tanminivan requested changes

2024-04-04 15:41 UTC, tanminivan commented on NavigationTools.py
> +from geopy.exc import *
Personally I'm not really a fan of star imports. Is there a way you can only import what you need?

2024-04-04 15:41 UTC, tanminivan commented on NavigationTools.py
> +                error_var = GeocoderQueryError("Error: Connection with the geocoding service timed out")
Why are you raising a `GeocoderQueryError` when a `GeocoderTimedOut` exception was raised?

2024-04-11 17:18 UTC, SirFlarflajon commented on NavigationTools.py
> +from geopy.exc import *
geopy.exc includes all the errors we can use so I felt it would be easier to import all the errors as one instead of multiple import lines per error

2024-04-11 17:20 UTC, SirFlarflajon commented on NavigationTools.py
> +                error_var = GeocoderQueryError("Error: Connection with the geocoding service timed out")
That was a typo I forgot to fix, should be fixed now.

2024-04-11 17:24 UTC, SirFlarflajon commented on NavigationTools.py
> +                raise error_var
So are you suggesting just have it as one exception catch and it prints the default error message for each?

2024-04-11 19:17 UTC, tanminivan commented on NavigationTools.py
>          if not(isinstance(longitude, (float, int))) :
Any response to this, @SirFlarflajon ?

2024-04-11 19:17 UTC, tanminivan commented on NavigationTools.py
> +            except GeocoderQueryError as e :
Any response to this, @SirFlarflajon ?

2024-04-11 19:17 UTC, tanminivan commented on NavigationTools.py
> +                error_var = GeopyError(f"Error: Geocode failed on {location} with error message {e}")
Any response to this, @SirFlarflajon ?

2024-04-11 19:17 UTC, tanminivan commented on NavigationTools.py
> +                location_geocode = GEOLOCATOR.geocode(location)
Any response to this, @SirFlarflajon ?

2024-04-11 19:37 UTC, tanminivan commented on NavigationTools.py
> +                raise error_var
I could see two ways.

# Way 1

You could have one catch clause for _all_ GeoPy-related errors. From the docs page, [it appears that each exception extends from `GeopyError`](https://geopy.readthedocs.io/en/stable/#geopy.exc.GeopyError). So you could catch `GeopyError`, log a generic message about some geopy-related error, and raise it again:

```python
try :
    print( "Geocoding {location}..." ) # you've already logged it here, so it should be pretty straight forward to tell from the logs what location caused the problem
    location_geocode = GEOLOCATOR.geocode(location)
except GeopyError as err:
    print( "ERROR: An error occurred while geocoding {location}" )
    raise err
```

This ensures that whatever the original exception was (`GeocoderServiceError`, `GeocoderQueryError`, etc.), we'll know about it when it gets raised. There's really no handling differentiation between these exception types (that is, you don't do one thing when you get a `GeocoderTimedOut` vs doing another thing when you get a `GeocoderUnvailable`). So why support all of this code when we do the same thing, regardless of the exception thrown? Catch the parent exception, log about it, and re-raise it.

# Way 2

The second way is similar, but just adds specific logging about each type:

```python
try :
    ...
except Exception1 as err:
    print( "ERROR: Got Exception1, is <something> right?" )
    raise err
except Exception2 as err:
    print( "ERROR: Got Exception2, is <something> right? Are you connected?" )
    raise err
except Exception3 as err:
    print( "ERROR: Got Exception3, is <something> right? Was the input invalid?" )
    raise err
except Exception4 as err:
    print( "ERROR: Got Exception4, is <something> right? Are you authenticated?" )
    raise err
```

In each of these, you can log some specific message that gives a hint to what the problem might be. But the distinction here is that we just re-raise the exception immediately instead of using `error_var`.

2024-04-11 19:47 UTC, SirFlarflajon commented on NavigationTools.py
> +                raise error_var
I can look into those ways instead, I see what you mean now.

2024-04-15 03:59 UTC, SirFlarflajon commented on NavigationTools.py
> +                raise error_var
Decided to go with the first way you mentioned as I think seeing the specific message involved would be more useful overall

2024-04-15 04:00 UTC, SirFlarflajon commented on NavigationTools.py
>          location: a string (KOKC airport code or address) to convert to a set of coordinates
I fixed the comment that was there prior to fit more with what should fit.

2024-04-15 04:03 UTC, SirFlarflajon commented on NavigationTools.py
>          if not(isinstance(longitude, (float, int))) :
I removed the added ones as I was told we already handle the cases of them being none and also changed the following errors to return error types instead.

2024-04-15 04:05 UTC, SirFlarflajon commented on NavigationTools.py
> +                error_var = GeopyError(f"Error: Geocode failed on {location} with error message {e}")
So while I am condesing them into one error catch, there are some slight differences in how they run. How I had it prior it would start with the most specific/common errors and then go to more vague ones.

2024-04-15 04:13 UTC, SirFlarflajon commented on NavigationTools.py
> +                location_geocode = GEOLOCATOR.geocode(location)
Just added a check to see if the location_geocode is None, I didn't see anything in the errors about checking for a None result

2024-04-15 18:27 UTC, Zombiepro89 requested changes

2024-04-15 18:27 UTC, Zombiepro89 commented on notamFetch.py
Consider dropping these changes. In main, the `is_valid_US_airport_code` function uses the library and variable that is deleted.

2024-04-16 16:35 UTC, SirFlarflajon commented on notamFetch.py
So you want me to put them back to how it was before? Just making sure

2024-04-16 17:04 UTC, Zombiepro89 commented on notamFetch.py
Yeah, that's right.

2024-04-16 17:05 UTC, Zombiepro89 approved these changes

2024-04-16 18:43 UTC, aidanperkins approved these changes

2024-04-16 18:50 UTC, tanminivan approved these changes

2024-04-16 18:52 UTC, tanminivan commented
Don't forget to squash and rebase.

2024-04-16 19:46 UTC, JamesJWilliams3000 approved these changes

2024-04-16 19:46 UTC, Zenpock approved these changes

2024-04-16 19:47 UTC, MinhTeeFresh approved these changes

2024-04-16 20:05 UTC, merged