[KAN-46] Create unit tests for testing speed of program execution
OU2024Capstone/notamSort pull request #35
Opened 2024-04-18 19:09 UTC by SirFlarflajon

Adding efficiency tests to run to make sure our code is running under 30 seconds with any given input, no matter the distance.

2024-04-18 19:38 UTC, JamesJWilliams3000 requested changes

2024-04-18 19:38 UTC, JamesJWilliams3000 commented on tests/notamTests.py
>  from io import StringIO
StringIO is imported twice.

2024-04-18 19:38 UTC, JamesJWilliams3000 commented on tests/notamTests.py
> +    fake_output = StringIO()
Kinda nit-picky, but maybe we could rename it to `dummy_output`? Maybe put a comment explaining that the script requires an output object, but the tests don't need to access it, hence the dummy output.

2024-04-18 20:28 UTC, SirFlarflajon commented on tests/notamTests.py
> +    fake_output = StringIO()
Yeah that makes sense, there is also a comment above the class that uses it more about why it's there but I can add one above the other class as well

2024-04-18 20:29 UTC, SirFlarflajon commented on tests/notamTests.py
>  from io import StringIO
Removed it, thanks!

2024-04-18 20:33 UTC, Zombiepro89 approved these changes

2024-04-19 19:37 UTC, JamesJWilliams3000 approved these changes

2024-04-21 22:21 UTC, Zenpock approved these changes

2024-04-22 20:56 UTC, aidanperkins approved these changes

2024-04-23 19:25 UTC, merged