[KAN-17] Added a map with the flight route and all the points we collect notams from
OU2024Capstone/notamSort pull request #40
Opened 2024-04-23 04:43 UTC by aidanperkins

Added a map that focuses on the US. It draws an accurate flight path from any 2 locations in the US and adds all the points we collected NOTAMs from. You can view the latitude and longitude of the points when you hover over them too

2024-04-23 18:56 UTC, SirFlarflajon approved these changes

2024-04-24 00:27 UTC, Zombiepro89 requested changes
If the application encounters an error, older queries will still be drawn the next time the user sends a query. Try making a function that clears the map where we clear the log.

2024-04-24 01:52 UTC, Zombiepro89 approved these changes

2024-04-25 18:41 UTC, Zenpock approved these changes

2024-04-25 19:08 UTC, MinhTeeFresh approved these changes

2024-04-25 20:38 UTC, merged