[KAN-70] implement radius digit check
OU2024Capstone/notamSort pull request #41
Opened 2024-04-23 18:45 UTC by MinhTeeFresh

Implemented a check to ensure that given radius is a digit that can be used to contribute to score. Previously had some cases that would contain letters, for unknown reason. May be involved with international travel, which does not apply to this project.

2024-04-23 18:58 UTC, SirFlarflajon approved these changes

2024-04-23 18:59 UTC, JamesJWilliams3000 approved these changes

2024-04-23 19:14 UTC, MinhTeeFresh commented on NotamSort.py
> +            return False
Radius scores are really low compared to other score cases. The difference of 5 points where the max of others are around 100-1000. In this case, we lack documentation for how to deal with letter radius cases. So I think it wouldn't be a massive loss of distinguishing scores by losing radius.

2024-04-25 16:19 UTC, aidanperkins commented on NotamSort.py
> +            return False
I think we still want to score the case where we have a radius containing 'IC'. Since those are restricted flight zones they're probably pretty important.

2024-04-25 16:20 UTC, aidanperkins requested changes
We should probably still score NOTAMs that have restricted flight zones where the radius contains 'IC'

2024-04-25 18:33 UTC, Zenpock approved these changes

2024-04-25 19:06 UTC, aidanperkins approved these changes

2024-04-25 19:51 UTC, merged