[Kan-74] Division by zero bug fix
OU2024Capstone/notamSort pull request #43
Opened 2024-04-24 18:32 UTC by MinhTeeFresh

Catching the exceptions led by accessing an invalid value in the json file, default value added as 'MinValue' on each category based on a score lower than the lowest score allowed by each category.

2024-04-24 18:37 UTC, SirFlarflajon approved these changes

2024-04-25 18:43 UTC, Zombiepro89 requested changes

2024-04-25 18:43 UTC, Zombiepro89 commented on NotamSort.py
>              score += 10 / difference_in_days
This could be zero if the NOTAM expires on the day of the search.

2024-04-25 19:56 UTC, Zombiepro89 approved these changes

2024-04-25 22:52 UTC, Zenpock approved these changes

2024-04-26 21:42 UTC, merged