[KAN-79] Moved to Using a Database file for Airport Validation
OU2024Capstone/notamSort pull request #49
Opened 2024-04-26 21:10 UTC by Zombiepro89

[NOTE] Please extensively test this branch, let's make sure that we don't have any missing US airports.

Geopy had some airports that it could not detect. After testing with the airportsdata library and discovering that it had the same issue, I moved to a database file which can be found [here](https://adds-faa.opendata.arcgis.com/datasets/faa::airports-1/explore).

So far, every airport that i've tested has been found, including previously problematic airports such as PWM, EYW, 1k4, 1k5, and LAS. However, extensive testing should be done to attempt to find any holes in this database file.

2024-04-28 00:46 UTC, SirFlarflajon commented on NotamFetch.py
>  # geolocator API agent for coordinates
Just a small thing so comments are consistent, should this mention the database and not the geolocator?

2024-04-28 00:46 UTC, SirFlarflajon approved these changes

2024-04-28 01:26 UTC, Zombiepro89 commented on NotamFetch.py
>  # geolocator API agent for coordinates
Yeah, that's good catch. I'll patch that real quick.

2024-04-28 01:39 UTC, aidanperkins reviewed
We should load the database in at the __init__ function of NavigationTools.py. All of our function calls with the database come from there anyway

2024-04-28 01:41 UTC, aidanperkins commented on NotamFetch.py
> +    file.close()
This section can just be moved to NavigationTools.py->__init__

2024-04-28 14:23 UTC, Zombiepro89 commented on NotamFetch.py
> +    file.close()
We could move it inside NavigationTools, but where would we call it? We only want to call this function 1 time, because loading the database is very costly. The only solution I can think of is loading it inside of NotamFetch when we create our constants.

2024-04-28 17:17 UTC, aidanperkins commented on NotamFetch.py
> +    file.close()
Putting it in the NavigationTools _init_ function should only load it when we import the class

2024-04-28 17:24 UTC, Zombiepro89 commented on NotamFetch.py
> +    file.close()
The only init function I see in that script is inside the PointObject class. That init function runs every time we create a PointObject.

2024-04-28 17:38 UTC, aidanperkins commented on NotamFetch.py
> +    file.close()
Try defining another \_\_init\_\_ function outside of the PointObject class that loads the database.

2024-04-28 17:42 UTC, Zombiepro89 commented on NotamFetch.py
> +    file.close()
We would still need to call it somewhere. The __init__ function is something inherent to objects and they are called each time a new instance of an object is created. For scripts, they don't have this. Whatever isn't in a function or class is run on initialization.

2024-04-28 17:53 UTC, aidanperkins commented on NotamFetch.py
> +    file.close()
Thats true, in that case I think you can call that function inside NavigationTools or move the code outside the function so it gets run when the constants are defined. Then we'd also need to check if the database is already initialized in case NavigationTools is imported in another file.

2024-04-28 19:22 UTC, tanminivan commented on NotamFetch.py
> +    file.close()
Good discussion. You might also look into how you might get Flask to handle one-time initialization stuff.

2024-04-28 19:25 UTC, aidanperkins approved these changes

2024-04-29 17:12 UTC, JamesJWilliams3000 requested changes
Aside from the variable mix-up I found on line 107, I only had a couple nitpicks.

2024-04-29 17:12 UTC, JamesJWilliams3000 commented on NavigationTools.py
> +                is_ICAO_code = not curr_airport_code is None and curr_airport_code.upper() == user_input.upper()
The codes are mixed up here. `is_ICAO_code` is true for IATA/FAA codes, and `is_IATA_code` is true for ICAO codes.

2024-04-29 18:50 UTC, JamesJWilliams3000 approved these changes

2024-04-29 22:30 UTC, Zenpock approved these changes

2024-04-29 22:56 UTC, merged

2024-04-30 00:51 UTC, tanminivan commented on NavigationTools.py
> +            for airport in database:
Ouch, looping through 20,000+ results for EACH airport that we're checking? And doing all this computation below for EVERY RECORD? Costly. What this were a million or a billion airports?

You can use a filter to fetch only the airport you want from `database`:
```python
result = filter( lambda a: a["properties"]["IDENT"] == user_input, database )
```

You could also save a lot of effort if you pre-computed the data that you'd need when you load the database file.

Create your own dict that is `airport identifier` -> `airport properties list`, so something like:

```
# ENTRY 1
"1K4" →  {
        "OBJECTID": 11526,
        "GLOBAL_ID": "457D09FA-8B7C-4DAA-A5F5-38090A0880D2",
        "IDENT": "1K4",
        "NAME": "David Jay Perry",
        "LATITUDE": "35-09-18.2430N",
        "LONGITUDE": "097-28-13.4180W",
        ...
        "US_AREA": 0,
        "PACIFIC": 0
      }

# ENTRY 2
"OKC" →  {
        "OBJECTID": 11672,
        "GLOBAL_ID": "43959DC9-0966-4841-A6F7-B8A784242500",
        "IDENT": "OKC",
        "NAME": "Will Rogers World",
        "LATITUDE": "35-23-35.0665N",
        "LONGITUDE": "097-36-02.7422W",
        ...
        "US_AREA": 0,
        "PACIFIC": 0
      },
etc.
```

As you're building this list, throw out all airports that aren't in the continental US.

Now this code simply becomes:
```python
airport = user_input.upper()
if airport not in db:
    # invalid airport, not in continental US, log error, raise exception, whatever you want, etc
else:
    airport_latitude = db[airport]["LATITUDE"]
    airport_longitude = db[airport]["LONGITUDE"]
    # etc
```

Sorry for the necropost here.