Kan 24
OU2024Capstone/notamSort pull request #7
Opened 2024-02-15 19:49 UTC by aidanperkins

Refactoring the script to be callable from the flask front end.

2024-02-15 20:17 UTC, JamesJWilliams3000 approved these changes

2024-02-15 20:55 UTC, Zenpock approved these changes

2024-02-15 20:57 UTC, Zombiepro89 approved these changes
Looks good. Just a suggestion, changing 'notam_num' -> 'num_notam' and 'page_num' -> 'num_page' is a bit easier to read.

2024-02-16 04:46 UTC, tanminivan commented
Going to copy in my original comments here, so I can mark them as resolved.

2024-02-16 04:51 UTC, tanminivan requested changes

2024-02-16 04:51 UTC, tanminivan commented on notamFetch.py
>  import json
Not a big deal, but I'd rename the branch name to simply `KAN-24` if you can. It'll make things easier on us in the future when we're rebasing/doing git command line.

2024-02-16 04:51 UTC, tanminivan commented on notamFetch.py
>  import json
Also don't forget to format your commit message like `[KAN-24] <description here>`

2024-02-16 04:51 UTC, tanminivan commented on notamFetch.py
> +# call me to populate and return the notam list
_All_ notams? Notams from departure and destination and the ones in between?

2024-02-16 04:51 UTC, tanminivan commented on notamFetch.py
> +def get_notams(departure_airport, arrival_airport) :
If we're going to use python, we should stick with pythonic conventions. PEP8 lays out these conventions. The pythonic way would be `get_notams`, `dep_ap`, `arr_ap`.

PEP8: https://peps.python.org/pep-0008/

2024-02-16 04:51 UTC, tanminivan commented on notamFetch.py
> +def get_notams(departure_airport, arrival_airport) :
Personally, I'm not a fan of extremely short variable names for the sake of extremely short variable names. 😄 `departure_airport` and `arrival_airport` succinctly describe what these variables represent and do not make the reader guess what they mean. Remember that code is read a thousand times more often than it is written.

I will say too, we should definitely figure out and agree on consistent naming during this project. We have been pretty consistent on "Departure". "Arrival" is fine—I'm used to saying "destination" so I'll probably let that slip once and a while but as long as everyone stays consistent it's fine.

2024-02-16 04:51 UTC, tanminivan commented on notamFetch.py
> +    geoLocator = Nominatim(user_agent="notam_sort")
`user_agent`? Is this making a web call to resolve these coordinates? If so, what happens if that external resource is unavailable?

2024-02-16 04:51 UTC, tanminivan commented on notamFetch.py
> +    geoLocator = Nominatim(user_agent="notam_sort")
Devil will be in the details for these sorts of things. 😄

How do you know that this is accurate?

Say it _is_ "accurate"—do we know what geodetic datum they are using to make this translation? Does that match up with what the FAA API is expecting?

What is the precision of the resulting coordinates and will this work for our application?

2024-02-16 04:51 UTC, tanminivan commented on notamFetch.py
> +    departure_airport_location = geoLocator.geocode(departure_airport)
Woah, woah, woah. First `depAP` is going to be an airport code like `OKC` but now we're redefining it to be some sort of coordinate object? There's no way that could lead towards subtle bugs, could it? :)

2024-02-16 04:51 UTC, tanminivan commented on notamFetch.py
> +    }
Yep we'll have to change this later on how we read these credentials.

2024-02-16 04:51 UTC, tanminivan commented on notamFetch.py
> +    }
What happens if these credentials don't exist?

2024-02-16 04:51 UTC, tanminivan commented on notamFetch.py
> +    faa_api_input = {
Avoid vague variable names.

2024-02-16 04:51 UTC, tanminivan commented on notamFetch.py
> +        "locationLatitude" : str(departure_airport_location.latitude),
Why get the lat/long when the API natively supports querying by airport code? This is also likely to get many more notams than desired if multiple airports are clustered closely together within a 25 mile radius.

2024-02-16 04:51 UTC, tanminivan commented on notamFetch.py
> +    api_result = requests.get(url=faa_api, params=faa_api_input , headers=credentials)
What if this URL changes and we have to dig through all of our code and replace each instance of it? Could we better define this so it is easier to change?

2024-02-16 04:51 UTC, tanminivan commented on notamFetch.py
> +        raise Exception("bad return code")
I know we're still in early stages but give serious thought to exception handling. What should happen now that we don't have data? Is this returned to the user in some way?

These are some questions to answer later, not as part of this PR.

But a more applicable improvement for this PR is to include some more relevant details once we get an error:
This failed. What did we expect? What did we get instead? What were the useful details as part of our request?

Good logging/exception handling can help us figure out future problems much more quickly than vague error messages.

2024-02-16 04:51 UTC, tanminivan commented on notamFetch.py
> +    departure_airport_notam_dict = json.loads(api_output)
vague variables names. What is this data that we got?

2024-02-16 04:51 UTC, tanminivan commented on notamFetch.py
> +    page_num = departure_airport_notam_dict.get("pageNum")
We get the page number, but do we ever do anything with it?

2024-02-16 04:51 UTC, tanminivan commented on notamFetch.py
> +        current_notam_properties = current_notam.get("properties").get("coreNOTAMData").get("notam")
As we're drilling through this data, are we certain that each of these keys exist for every record? What happens if one of them is missing?

2024-02-16 04:51 UTC, tanminivan commented on notamFetch.py
> +    return full_notam_list
This is a good start, but how can we move away from "a collection of python scripts" and towards "a well-designed software architecture"?

If we encapsulated this functionality into a class, what would that look like? What would be its responsibility? What kind of public methods would we expose? What kind of private helper methods would we create? What kind of data would we store in instance variables?

2024-02-16 04:55 UTC, tanminivan requested changes

2024-02-16 04:55 UTC, tanminivan commented on notamFetch.py
> +    departure_airport_location = geoLocator.geocode(departure_airport)
`location` is good, but what about `coordinates`? More accurate? last accurate?

2024-02-16 04:55 UTC, tanminivan commented on notamFetch.py
> +    geoLocator = Nominatim(user_agent="notam_sort")
Small thing but the pythonic way would be either `geo_locator` or simply `geolocator`

2024-02-16 04:55 UTC, tanminivan commented
Reviewed again, a few things. Which things do you think you could solve now? Which should be broken out into subsequent tickets?

2024-02-16 04:57 UTC, tanminivan commented
> Looks good. Just a suggestion, changing 'notam_num' -> 'num_notams' and 'page_num' -> 'num_pages' is a bit easier to read.

Good suggestion, @Zombiepro89

2024-02-16 21:52 UTC, tanminivan requested changes
I commented on things I'd really like to see an answer on (either code fixes or a separate ticket) before approving:

1. Why are we converting to coordinates when the API supports querying via an airport identifier?

2. What about the page numbers in the API response?

3. We'll need to squash and rebase before merge! 🎉

2024-02-16 21:52 UTC, tanminivan commented on notamFetch.py
> +        "locationLatitude" : str(departure_airport_location.latitude),
I'd really like to hear an answer on this question  before I approve.

2024-02-16 21:52 UTC, tanminivan commented on notamFetch.py
> +    num_pages = departure_airport_notam_dict.get("pageNum")
We get the page number, but do we ever do anything with it?

2024-02-16 21:52 UTC, tanminivan commented on notamFetch.py
> +    num_pages = departure_airport_notam_dict.get("pageNum")
I'd really like to hear an answer on this question before I approve.

2024-02-16 21:57 UTC, aidanperkins commented on notamFetch.py
> +    num_pages = departure_airport_notam_dict.get("pageNum")
In order to use the locationRadius parameter of the FAA API its required we use the latitude and longitude and not the airport code, the API throws an error if you try. num_pages could be useful later if we change how we get the data when we have a large number of notams, currently we only retrieve 100 from the API.

2024-02-16 22:07 UTC, tanminivan commented on notamFetch.py
> +    num_pages = departure_airport_notam_dict.get("pageNum")
> In order to use the locationRadius parameter of the FAA API its required we use the latitude and longitude and not the airport code, the API throws an error if you try.

That makes sense. I think there's some value in a future discussion on querying via coordinates or via airport codes (maybe you would want your departure/arrival airports to be ranked higher in some way, and that would help you sort those out.). A conversation for another day! 

> num_pages could be useful later if we change how we get the data when we have a large number of notams, currently we only retrieve 100 from the API.

What happens if we try to retrieve 101 notams from the API? Does this code handle that?

2024-02-16 22:24 UTC, aidanperkins commented on notamFetch.py
> +    num_pages = departure_airport_notam_dict.get("pageNum")
Right now the number of notams we retrieve per call is hard coded in, ideally we'll ask the API for all of them but later can just specify some max number like 10,000.

2024-02-16 22:26 UTC, aidanperkins commented on notamFetch.py
> +    num_pages = departure_airport_notam_dict.get("pageNum")
Or we can ask for multiple pages an iterate through them. Since we're undecided and might want to display the notams in a list we might prefer the page method later.

2024-02-16 22:53 UTC, tanminivan commented on notamFetch.py
> +    num_pages = departure_airport_notam_dict.get("pageNum")
Nice, so it sounds like we _know_ we'll need to handle a large amount of NOTAMs one day, either by increasing the page size (What if there are 10,001 NOTAMs? Will the API even support returning that many results as one page?) or by supporting paging. We should ensure that work is captured in a new ticket so we don't forget.

2024-02-17 23:26 UTC, tanminivan approved these changes

2024-02-18 20:40 UTC, tanminivan commented
What are we waiting on in this PR?

2024-02-20 04:47 UTC, tanminivan commented
@aidanperkins Looks like you've got some conflicts here, let me know if you need some help resolving those on squash/rebase.

2024-02-20 16:29 UTC, merged