[Kan-25] Retrieve API secrets from env file
OU2024Capstone/notamSort pull request #8
Opened 2024-02-16 21:42 UTC by MinhTeeFresh

2024-02-16 21:43 UTC, MinhTeeFresh commented
I may need to add some comments to the code, but I primarily wanted a review on the README changes, does it make sense for new users?

2024-02-16 22:10 UTC, tanminivan requested changes

2024-02-16 22:10 UTC, tanminivan commented on README.md
> +This can be done by creating a .env file in the root directory </br>
Did you add the `.env` file to the `.gitignore`?

2024-02-16 22:12 UTC, tanminivan reviewed
Did this PR automatically add reviewers or did you have to review them manually, @MinhTeeFresh ? (great username btw)

2024-02-16 22:16 UTC, tanminivan commented
Man, I hit the wrong thing, I just wanted to add a comment, but requested changes instead, now it appears I can't change my vote? Thanks github.

2024-02-17 19:54 UTC, JamesJWilliams3000 approved these changes

2024-02-17 20:01 UTC, MinhTeeFresh commented
> Did this PR automatically add reviewers or did you have to review them manually, @MinhTeeFresh ? (great username btw)

No, I manually added the reviewers

2024-02-18 16:58 UTC, aidanperkins approved these changes

2024-02-18 17:05 UTC, Zombiepro89 approved these changes

2024-02-18 17:09 UTC, Zenpock approved these changes

2024-02-18 20:23 UTC, tanminivan commented on README.md
> +This can be done by creating a .env file in the root directory </br>
Ah, yeah, you are correct. It's already being ignored. Don't forget to squash and rebase.

2024-02-18 20:23 UTC, tanminivan approved these changes

2024-02-20 02:52 UTC, merged